Protected against TypeError: String required
Exception in thread Thread-70:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/home/evandro_coan/.config/sublime-text-3/Packages/HighlightWordsOnSelection/word_highlight.py", line 237, in wh_loop
    highlight_occurences( view )
  File "/home/evandro_coan/.config/sublime-text-3/Packages/HighlightWordsOnSelection/word_highlight.py", line 853, in highlight_occurences
    view.add_regions( 'HighlightWordsOnSelection', word_regions, Pref.color_scope_name( settings ), gutter, draw_outlined )
  File "/opt/sublime_text/sublime.py", line 1064, in add_regions
    sublime_api.view_add_regions(self.view_id, key, regions, scope, icon, flags)
TypeError: String required